[package]
name = "ibis"
version = "0.1.0"
edition = "2021"

[features]
ssr = [
  "activitypub_federation",
  "axum",
  "axum-macros",
    "tower-http",
  "diesel",
  "diesel-derive-newtype",
  "diesel_migrations",
    "tokio",
  "leptos_axum"
]
csr = ["leptos/csr", "leptos_meta/csr", "leptos_router/csr"]

[dependencies]
# shared
serde = { version = "1.0.192", features = ["derive"] }
url = { version = "2.4.1", features = ["serde"] }
reqwest = { version = "0.11.22", features = ["json"] }
log = "0.4"

# backend
activitypub_federation = { version = "0.5.0-beta.6", features = [
  "axum",
  "diesel",
], default-features = false, optional = true }
anyhow = "1.0.75"
async-trait = "0.1.74"
axum = { version = "0.6.20", optional = true }
axum-macros = { version = "0.3.8", optional = true }
bcrypt = "0.15.0"
chrono = { version = "0.4.31", features = ["serde"] }
diesel = { version = "2.1.4", features = [
  "postgres",
  "chrono",
  "uuid",
], optional = true }
diesel-derive-newtype = { version = "2.1.0", optional = true }
diesel_migrations = { version = "2.1.0", optional = true }
diffy = "0.3.0"
enum_delegate = "0.2.0"
env_logger = { version = "0.10.1", default-features = false }
futures = "0.3.29"
hex = "0.4.3"
jsonwebtoken = "9.2.0"
rand = "0.8.5"
serde_json = "1.0.108"
sha2 = "0.10.8"
tokio = { version = "1.34.0", features = ["full"], optional = true }
uuid = { version = "1.6.1", features = ["serde"] }
tower-http = { version = "0.4.0", features = ["cors"], optional = true }
leptos_axum = { version = "0.5.4", optional = true }

# frontend
leptos = { version = "0.5.4", features = ["nightly"] }
leptos_meta = { version = "0.5.4", features = ["nightly"] }
leptos_router = { version = "0.5.4", features = ["nightly"] }
console_log = "1"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["AbortController", "AbortSignal"] }

[dev-dependencies]
once_cell = "1.18.0"
pretty_assertions = "1.4.0"
reqwest = "0.11.22"

[package.metadata.leptos]
output-name = "ibis"
bin-features = ["ssr"]
lib-features = ["csr"]

[lib]
crate-type = ["cdylib", "rlib"]
