[package]
name = "fediwiki"
version = "0.1.0"
edition = "2021"

[dependencies]
activitypub_federation = { version = "0.4.7", features = ["axum"], default-features = false }
anyhow = "1.0.75"
async-trait = "0.1.74"
axum = "0.6.20"
axum-macros = "0.3.8"
chrono = { version = "0.4.31", features = ["serde"] }
enum_delegate = "0.2.0"
env_logger = { version = "0.10.1", default-features = false }
futures = "0.3.29"
rand = "0.8.5"
serde = "1.0.192"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
url = "2.4.1"

[dev-dependencies]
once_cell = "1.18.0"
reqwest = "0.11.22"
serial_test = "2.0.0"
